apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 5m
  url: https://kubernetes-charts.storage.googleapis.com/
